"""Remove unused operation_type column

Revision ID: 48cb575d966e
Revises: 5c15480feed0
Create Date: 2025-09-04 08:32:42.020085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cb575d966e'
down_revision: Union[str, Sequence[str], None] = '5c15480feed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'operation_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('operation_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
